<a href="https://colab.research.google.com/github/ravitejareddy-dodda/258-Deep-Learning-Group/blob/main/various_tensor_operations_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensors

In [1]:
import tensorflow as tf
import numpy as np

In [5]:
rank_0= tf.constant(6)
print(rank_0)

tf.Tensor(6, shape=(), dtype=int32)


In [7]:
rank_1= tf.constant([7.0, 8.0, 9.0])
print(rank_1)

tf.Tensor([7. 8. 9.], shape=(3,), dtype=float32)


In [8]:
rank_2 = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [10]:
rank_3 = tf.constant([
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],
  [[30, 31, 32, 33, 34],
   [35, 36, 37, 38, 39]],])

print(rank_3)

tf.Tensor(
[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]], shape=(3, 2, 5), dtype=int32)


converting tensor to array

In [11]:
np.array(rank_2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [12]:
rank_2.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

addition, element-wise multiplication, and matrix multiplication.

In [14]:
x = tf.constant([[1, 2],
                 [3, 4]])
y = tf.constant([[1, 1],
                 [1, 1]]) 
print(tf.add(x, y), "\n")
print(tf.multiply(x, y), "\n")
print(tf.matmul(x, y), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [15]:
print(x + y, "\n") # addition
print(x * y, "\n") # multiplication
print(x @ y, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [16]:
z = tf.constant([[4.0, 5.0], [10.0, 1.0]])

#largest value
print(tf.reduce_max(z))
#index of the largest value
print(tf.math.argmax(z))
# Compute the softmax
print(tf.nn.softmax(z))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [17]:
tf.convert_to_tensor([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [18]:
tf.reduce_max([1,2,3])

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [19]:
tf.reduce_max(np.array([1,2,3]))

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [20]:
rank_4 = tf.zeros([3, 2, 4, 5])

In [22]:
print("Type:", rank_4.dtype)
print("No. of axes:", rank_4.ndim)
print("Shape:", rank_4.shape)
print("Elements along axis 0:", rank_4.shape[0])
print("Elements along the last axis:", rank_4.shape[-1])
print("Total number of elements: ", tf.size(rank_4).numpy())

Type: <dtype: 'float32'>
No. of axes: 4
Shape: (3, 2, 4, 5)
Elements along axis 0: 3
Elements along the last axis: 5
Total number of elements:  120


In [23]:
tf.rank(rank_4)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [24]:
tf.shape(rank_4)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5], dtype=int32)>

## Indexing

In [25]:
rank_1 = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


Indexing with a scalar removes the axis:

In [26]:
print("First:", rank_1[0].numpy())
print("Second:", rank_1[1].numpy())
print("Last:", rank_1[-1].numpy())

First: 0
Second: 1
Last: 34


Indexing with a `:` slice keeps the axis:

In [27]:
print("Everything:", rank_1[:].numpy())
print("Before 8:", rank_1[:8].numpy())
print("From 8 to the end:", rank_1[8:].numpy())
print("From 3, before 9:", rank_1[3:9].numpy())
print("Every other item:", rank_1[::2].numpy())
print("Reversed:", rank_1[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 8: [ 0  1  1  2  3  5  8 13]
From 8 to the end: [21 34]
From 3, before 9: [ 2  3  5  8 13 21]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


### Multi-axis indexing

In [28]:
print(rank_2.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [29]:

print(rank_2[1, 1].numpy())

4.0


In [30]:
# Get row and column
print("Second row:", rank_2[1, :].numpy())
print("Second column:", rank_2[:, 1].numpy())
print("Last row:", rank_2[-1, :].numpy())
print("First item in last column:", rank_2[0, -1].numpy())
print("Skip the first row:")
print(rank_2[1:, :].numpy(), "\n")

Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [33]:
print(rank_3[:, :, 3])

tf.Tensor(
[[13 18]
 [23 28]
 [33 38]], shape=(3, 2), dtype=int32)


In [34]:

a = tf.constant([[1], [2], [3]])
print(a.shape)

(3, 1)


In [35]:

print(a.shape.as_list())

[3, 1]


In [36]:

reshaped = tf.reshape(a, [1, 3])

In [37]:
print(a.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [38]:
print(rank_3)

tf.Tensor(
[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]], shape=(3, 2, 5), dtype=int32)


In [39]:

print(tf.reshape(rank_3, [-1]))

tf.Tensor(
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39], shape=(30,), dtype=int32)


In [43]:
print(tf.reshape(rank_3, [3*2, 5]), "\n")
print(tf.reshape(rank_3, [3, -1]))

tf.Tensor(
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]], shape=(3, 10), dtype=int32)


In [44]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


In [45]:

x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


without broadcasting:

In [46]:
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch)

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [47]:
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [48]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [49]:
try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


  `tf.RaggedTensor` using `tf.ragged.constant`:

In [50]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


In [51]:
print(ragged_tensor.shape)

(4, None)


scalar string tensor:

In [52]:

scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


vector of strings:

In [54]:

tensor_of_strings = tf.constant(["black toy",
                                 "Quic black cow",
                                 "Lazy donkey"])

print(tensor_of_strings)

tf.Tensor([b'black toy' b'Quic black cow' b'Lazy donkey'], shape=(3,), dtype=string)


In [56]:

print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [57]:

print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'black', b'toy'], [b'Quic', b'black', b'cow'], [b'Lazy', b'donkey']]>


In [58]:
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


In [61]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [62]:
unicode_bytes = tf.constant("アヒル 🦆")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)


Unicode bytes: tf.Tensor(b'\xe3\x82\xa2\xe3\x83\x92\xe3\x83\xab \xf0\x9f\xa6\x86', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'\xe3\x82\xa2' b'\xe3\x83\x92' b'\xe3\x83\xab' b' ' b'\xf0\x9f\xa6\x86'], shape=(5,), dtype=string)

Unicode values: tf.Tensor([ 12450  12498  12523     32 129414], shape=(5,), dtype=int32)


## Sparse tensors



In [63]:

sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")


print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
